# Generated by Django 2.2 on 2022-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sp', 'Spanish'), ('it', 'Italian')], default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='customers.Attribute'),
        ),
    ]
